### ISSUE TITLE
Add quick tasks without categories

### ISSUE THREAD

**Issue by digitalethics** [mivoligo/purple_task#1]
Thanks for the great app! Would you consider implementing a functionality to quickly add uncategorized tasks? Very simple tasks may not need a project category at all and could be listed separately in the dashboard/main screen. It may also be useful to be able to quickly add tasks and reorganize and categorize them later, perhaps via drag and drop?

**Comment by mivoligo** [comment]
Hi @digitalethics Sorry for the late reply. 
I was thinking about that but decided not to implement. Personally I have my first category set as "General" and I add there all kind of tasks not related to anything in particular.

**Comment by mivoligo** [comment]
Added in version 1.2.0. 
You can't move it to a category by drag&drop (yet) but you can change category in task's options.
